# -*- coding: utf-8 -*-
"""tiempo_gasolina.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dtRHEbDIJvAELLuAVtLO76Ebcx2jT4jw
"""

vdinero = 600
v_velocidad = 50.00

_vprecio = input('¿Cuál es el precio de la gasolina por litro?\n')
vprecio = float(_vprecio)

vlitros = vdinero/vprecio
_vrendimiento = input('¿Cuál es el rendimiento de tu vehículo? (Km/L)\n')
vrendimiento = float(_vrendimiento)

vdistancia = vrendimiento * vlitros
# Tiempo
vtiempo_decimal = vdistancia / v_velocidad
vhoras = int(vtiempo_decimal)

vminutos_decimal = (vtiempo_decimal - vhoras) * 60
vminutos = int(vminutos_decimal)

vsegundos_decimal = (vminutos_decimal - vminutos) * 60
vsegundos = int(vsegundos_decimal)

print(f'\n Dinero: {vdinero}')
print(f'''El tiempo que puedes recorrer en una distancia de {round(vdistancia, 2)}km
con {int(vlitros)} litros de gasolina a una velocidad de {v_velocidad} km/h
es de {vhoras} horas con {vminutos} minutos y {vsegundos} segundos''')